require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

Layout/LineLength:
  Max: 80

RSpec/ExampleWording:
  Enabled: false
