---
name: SleepingKingStudios::Docs::Commands::Generators::Base
slug: base
type: class
files:
- lib/sleeping_king_studios/docs/commands/generators/base.rb
parent_path: sleeping-king-studios/docs/commands/generators
short_description: Abstract base class for writing generator classes.
instance_attributes:
- name: docs_path
  read: true
  write: false
  path: sleeping-king-studios/docs/commands/generators/base/i-docs-path
  slug: docs-path
  inherited: false
- name: options
  read: true
  write: false
  path: sleeping-king-studios/docs/commands/generators/base/i-options
  slug: options
  inherited: false
instance_methods:
- name: dry_run?
  path: sleeping-king-studios/docs/commands/generators/base/i-dry-run?
  slug: dry-run?
  inherited: false
- name: force?
  path: sleeping-king-studios/docs/commands/generators/base/i-force?
  slug: force?
  inherited: false
- name: initialize
  path: sleeping-king-studios/docs/commands/generators/base/i-initialize
  slug: initialize
  inherited: false
  constructor: true
- name: template_path
  path: sleeping-king-studios/docs/commands/generators/base/i-template-path
  slug: template-path
  inherited: false
- name: verbose?
  path: sleeping-king-studios/docs/commands/generators/base/i-verbose?
  slug: verbose?
  inherited: false
- name: version
  path: sleeping-king-studios/docs/commands/generators/base/i-version
  slug: version
  inherited: false
data_path: sleeping-king-studios/docs/commands/generators/base
included_modules:
- name: Cuprum::ExceptionHandling
  slug: exception-handling
constructor: true
direct_subclasses:
- name: SleepingKingStudios::Docs::Commands::Generate
  slug: generate
  path: sleeping-king-studios/docs/commands/generate
- name: SleepingKingStudios::Docs::Commands::Generators::DataGenerator
  slug: data-generator
  path: sleeping-king-studios/docs/commands/generators/data-generator
- name: SleepingKingStudios::Docs::Commands::Generators::ReferenceGenerator
  slug: reference-generator
  path: sleeping-king-studios/docs/commands/generators/reference-generator
inherited_classes:
- name: Cuprum::Command
  slug: command
version: '0.1'
