---
name: SleepingKingStudios::Yard::Version::BUILD
parent_path: sleeping-king-studios/yard/version
slug: build
short_description: Build metadata.
value: nil
data_path: sleeping-king-studios/yard/version/build
metadata:
  api: private
version: "*"
