---
name: SleepingKingStudios::Docs::Version::BUILD
parent_path: sleeping-king-studios/docs/version
slug: build
short_description: Build metadata.
value: nil
data_path: sleeping-king-studios/docs/version/build
metadata:
  api: private
version: "*"
