---
plugins:
  - sleeping_king_studios/docs/jekyll/plugins/required
collections:
  classes:
    output: false
  constants:
    output: false
  methods:
    output: false
  modules:
    output: false
  namespaces:
    output: false
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'page'
    title: 'SleepingKingStudios::Docs'
exclude:
  - /vendor
description: |
  Tools for generating a versioned documentation site from YARD docs.
github:
  repository_url: https://github.com/sleepingkingstudios/sleeping_king_studios-docs # The sidebar link for the Dinky theme.
markdown: kramdown
theme: jekyll-theme-dinky
title: 'Docs' # The sidebar title for the Dinky theme.
project_metadata:
  name:           SleepingKingStudios::Docs
  repository_url: https://github.com/sleepingkingstudios/sleeping_king_studios-docs
  versions:
    - 0.1
    - 0.2
