---
collections:
  classes:
    output: false
  constants:
    output: false
  methods:
    output: false
  modules:
    output: false
  namespaces:
    output: false
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'default'
    title: 'SleepingKingStudios::Docs'
exclude:
  - /vendor
description: |
  Tools for generating a versioned documentation site from YARD docs.
github:
  repository_url: https://github.com/sleepingkingstudios/sleeping_king_studios-docs
markdown: kramdown
repository: sleepingkingstudios/sleeping_king_studios-docs
theme: jekyll-theme-dinky
title: 'Docs'
